server:
  port: 1000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/otniel-tamini/end-to-end-kubernetes-automation.git
          default-label: main
          searchPaths:
            - configuration
            - configuration/user-service
            - configuration/order-service
            - configuration/product-service