apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: e-commerce
spec:
  template:
    spec:
      containers:
      - name: api-gateway
        image: otniel217/api-gateway:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: CONSUL_HOST
          value: "consul"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-server:1000"