apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: e-commerce
  labels:
    app: order-service
    monitor: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        monitor: spring-boot
    spec:
      containers:
      - name: order-service
        image: otniel217/order-service:latest
        ports:
          - name: http-metrics
            containerPort: 1000
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-server:1000"
        - name: CONSUL_HOST
          value: "consul"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-db:3306/order_db?createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: e-commerce
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 1000
      targetPort: 1000