apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: e-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: otniel217/config-server:latest
        env:
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: "https://github.com/otniel-tamini/end-to-end-kubernetes-automation.git"
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
          value: "main"
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GIT_USER
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GIT_PASS