apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: e-commerce
  labels:
    app: user-service
    monitor: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        monitor: spring-boot
    spec:
      containers:
      - name: user-service
        image: otniel217/user-service:latest # Correction de l'image
        ports:
        - containerPort: 1000 # Port standard de tes services
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-server:1000"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://user-db:3306/user_db" # Pointe vers user-db
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: e-commerce
spec:
  selector:
    app: user-service
  ports:
    - port: 1000
      targetPort: 1000