apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: e-commerce
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 1000
      targetPort: 1000
  type: ClusterIP # Accessible uniquement à l'intérieur du cluster